### ISSUE TITLE
NameError: name 'file' is not defined

### ISSUE THREAD

**Issue by gulas2vladimir** [Rudd-O/zfs-tools#38]
file() is not supported in Python 3
zfstools/connection.py line 103
`p = SpecialPopen(cmd,stdin=file(os.devnull),stdout=subprocess.PIPE,bufsize=bufsize)`
fix:
`p = SpecialPopen(cmd,stdin=open(os.devnull),stdout=subprocess.PIPE,bufsize=bufsize)`
Thank you.

**Comment by Rudd-O** [comment]
Try 0.6.3 just tagged.
