### ISSUE TITLE
Speedup snapshot list

### ISSUE THREAD

**Issue by gulas2vladimir** [Rudd-O/zfs-tools#40]
Can you add specific dataset list instead of list all snapshot in __get_poolset_  functions please?
```shell
[zfs-tools]# time zfs list -Hpr -o name,creation -t all | wc -l

19574
real	2m17.044s
user	0m1.931s
sys	0m12.320s
```
instead of

```
[zfs-tools]# time zfs list -Hpr -o name,creation -t all pool/path | wc -l
126

real	0m0.354s
user	0m0.019s
sys	0m0.135s
```
Thank you for your job and time.

**Comment by Rudd-O** [comment]
Thanks, but unfortunately we need to get a full view of the pool in order to analyze the interdependencies between datasets (after all you may have cloned dataset pool/a from pool/b@snapshot) so this can't be done safely at this time to my knowledge.  Apologies.

**Comment by gulas2vladimir** [comment]
Ok. no problem. Thank you anyway.
