### ISSUE TITLE
deb package creation failure

### ISSUE THREAD

**Issue by tomposmiko** [Rudd-O/zfs-tools#6]
command: dpkg-buildpackage -uc -us
[...]
Creating tar archive
removing 'build/bdist.linux-x86_64/dumb' (and everything under it)
tar -C  zxvmf dist/zfs-tools-_.linux-_.tar.gz
tar: You must specify one of the `-Acdtrux' or`--test-label'  options
Try `tar --help' or`tar --usage' for more information.
make[1]: **\* [install] Error 2
make[1]: Leaving directory `/data/src/rudd-o-zfs-backup/zfs-tools'
dh_auto_build: make -j1 returned exit code 2
make: **\* [binary] Error 2
dpkg-buildpackage: error: debian/rules binary gave error exit status 2

First as you can see, DESTDIR isn't specified, so there is no argument for -C.

Then if it's specified in the Makefile:
[...]
Creating tar archive
removing 'build/bdist.linux-x86_64/dumb' (and everything under it)
tar -C /opt zxvmf dist/zfs-tools-_.linux-_.tar.gz
tar: You must specify one of the `-Acdtrux' or`--test-label'  options
Try `tar --help' or`tar --usage' for more information.
make[1]: **\* [install] Error 2
make[1]: Leaving directory `/data/src/rudd-o-zfs-backup/zfs-tools'
dh_auto_build: make -j1 returned exit code 2
make: **\* [binary] Error 2
dpkg-buildpackage: error: debian/rules binary gave error exit status 2

Using dash (-zxvmf) fixes the issue.

So doing again:
[...]
   dh_usrlocal
dh_usrlocal: debian/zfs-tools/usr/local/bin/zreplicate is not a directory
dh_usrlocal: debian/zfs-tools/usr/local/bin/zfs-shell is not a directory
dh_usrlocal: debian/zfs-tools/usr/local/bin/zsnap is not a directory
    "rmdir debian/zfs-tools/usr/local/bin"
rmdir: failed to remove ‘debian/zfs-tools/usr/local/bin’: Directory not empty
dh_usrlocal: rmdir debian/zfs-tools/usr/local/bin returned exit code 1
make: **\* [binary] Error 1

I don't find, why it is local, unfortunately I'm not familiar with packaging.

Distributor ID: Ubuntu
Description:    Ubuntu 13.10
Release:    13.10
Codename:   saucy

**Comment by Rudd-O** [comment]
Did you confirm that packaging is not broken anymore?

**Comment by tomposmiko** [comment]
I don't know, I have not tried it for a while.
